### ISSUE TITLE
vanilla wood items not minable with axe

### ISSUE THREAD

**Issue by VinceKezel** [LieOnLion/More-Chest-Variants#1]
When this mod is installed, some wood items do not mine faster with an axe. For example, the crafting table or spruce log when being mined with a diamond axe it goes as slow as the same speed as being mined with an empty hand.

In my troubleshooting, If I delete the following file from the MCV jar file then the axe works as intended, but then of course MCV chests dont go faster when mined with an axe:
_/src/main/resources/data/minecraft/tags/blocks/mineable/axe.json_

Minecraft 1.20.1
Fabric 0.14.22
MCV 1.2.1    Aug 26 2023

**Comment by LieOnLion** [comment]
I'm sorry for not seeing this, has It been fixed?

**Comment by TacocaTYT** [comment]
this issue is still present

**Comment by LieOnLion** [comment]
I am sorry but I am not experiencing any issues, what version are you using now?

**Comment by LieOnLion** [comment]
It works fine for me, if it keeps persisting, please open a new issue
