### ISSUE TITLE
Windows defender detects 1.5.1 for 1.20.1 as a trojan and deletes it instantly

### ISSUE THREAD

**Issue by Bloodymight** [LieOnLion/More-Chest-Variants#11]
Hi, 
my windows defender and chrome detects the latest version of your mod as a virus/trojan "Trojan:Script/Wacatac" and deletes it

your 1.20.4 upload seems to be fine, only the 1.20.1 upload gets detected

repackaging your 1.20.1 upload fixed the issue for me, so you might want to try that and reupload, since I am not the only one affected by this problem

![image](https://github.com/LieOnLion/More-Chest-Variants/assets/106433959/46cde419-9bce-4408-bd15-195ba23f2df4)

**Comment by LieOnLion** [comment]
Can you give me more information?
like CurseForge or Modrinth, if its only 1, can you test the other?

and how many people do you know (if any) are also getting the problem

**Comment by LieOnLion** [comment]
also the source code on here is rather outdated, I will update it next time I get the chance
