### ISSUE TITLE
Crashes when loading world

### ISSUE THREAD

**Issue by 1Lir0n** [LieOnLion/More-Chest-Variants#15]
i played with the 1.4.1 version of the mod and the BOP version(latest) and everything was and still is fine but when updating to the new version of the MCV it crashes while loading the world.
it says it a render issue.
this is the crash report:
[crash-2024-05-29_00.25.09-client.txt](https://github.com/LieOnLion/More-Chest-Variants/files/15476637/crash-2024-05-29_00.25.09-client.txt)

Currently I'm playing with the latest release version of MCV-BOP(1.0.0) and the 1.4.1 version of MCV, and it works ok
should i update to the beta?

**Comment by LieOnLion** [comment]
Yes, due to changes in MCV 1.5.1, it would crash the BOP addon.
Please use the beta file, but backup worlds as well!
