### ISSUE TITLE
Most Trapped Chests Have A Missing Texture

### ISSUE THREAD

**Issue by MiloMiko** [LieOnLion/More-Chest-Variants#17]
I downloaded the mod from modrinth, but when i booted up the game and in searched chests in my inventory, this is what showed up:
![Zrzut ekranu 2024-06-23 112626](https://github.com/LieOnLion/More-Chest-Variants/assets/161062432/b1d6d031-905b-49ce-ae09-13ee02c39ca7)
![Zrzut ekranu 2024-06-23 112612](https://github.com/LieOnLion/More-Chest-Variants/assets/161062432/a17134a9-3ea6-4e8f-aec4-379e81f33c82)
![Zrzut ekranu 2024-06-23 112602](https://github.com/LieOnLion/More-Chest-Variants/assets/161062432/28956d42-198b-41dc-b3e5-0b3cb091092e)
![Zrzut ekranu 2024-06-23 112552](https://github.com/LieOnLion/More-Chest-Variants/assets/161062432/dd6b4f66-5213-4cd0-866f-28253e954dee)
![Zrzut ekranu 2024-06-23 112543](https://github.com/LieOnLion/More-Chest-Variants/assets/161062432/18644067-a0ed-451f-8c97-e7ecc8dc3962)

Minecraft Version: 1.19.2
Mod Version: 1.5.0-beta.2
Forge Version: 1.19.2-43.3.2

**Comment by LieOnLion** [comment]
I am not supporting 1.19.2 anymore
