### ISSUE TITLE
incompatible with wood from regions unexplored

### ISSUE THREAD

**Issue by liamwerk7676** [LieOnLion/More-Chest-Variants#19]
what the title says 
![image](https://github.com/user-attachments/assets/5a60092c-a0b0-4172-92f9-2c5a17052d53)

**Comment by LieOnLion** [comment]
This is an issue im currently unsure how to fix, so don't expect it to be soon unfortunately.

If you are using Forge 1.20.1, use https://www.curseforge.com/minecraft/mc-mods/every-compat

**Comment by liamwerk7676** [comment]
ok thanks that did fix it
