### ISSUE TITLE
Game shuts down

### ISSUE THREAD

**Issue by Skijunkie85** [LieOnLion/More-Chest-Variants#6]
Hi.

When i start the game with the mod activated, it shuts down before i get to the startmenu.
I'm playing with the version 1.20.4.

Greets Skijunkie

**Comment by LieOnLion** [comment]
I believe I have fixed it, 1.5.1 will hopefully be out in the coming days

**Comment by LieOnLion** [comment]
Should be fixed with newer versions of Quad
