### ISSUE TITLE
Cannot craft vanilla trapped chest

### ISSUE THREAD

**Issue by Bloodymight** [LieOnLion/More-Chest-Variants#9]
When playing a vanilla chest and a tripwire into the crafting table nothing happens.

![grafik](https://github.com/LieOnLion/More-Chest-Variants/assets/106433959/43c9daa9-96b4-49b2-9f1d-7e3ab2bed684)

It also only shows an empty crafting table, when checking for the vanilla trapped chest recipe

![grafik](https://github.com/LieOnLion/More-Chest-Variants/assets/106433959/c110e999-df96-4760-a036-329bf0a5e0b3)

Edit:
it seems to be working with your chest variants, at least with the oak chest as seen here:

![grafik](https://github.com/LieOnLion/More-Chest-Variants/assets/106433959/a861681b-0b85-4963-89a7-baa01c7f3c5e)

Edit 2:
The Oak Trapped Chest only turns into a normal vanilla chest not into a vanilla trapped chest as one would expect:

![grafik](https://github.com/LieOnLion/More-Chest-Variants/assets/106433959/d5d9cdc9-55bd-481c-a8f4-fa708b523c53)

![grafik](https://github.com/LieOnLion/More-Chest-Variants/assets/106433959/b7cb4b7d-b7c6-45d7-b665-7fdeaaf234e4)

**Comment by LieOnLion** [comment]
thats good to know, will fix it in 1.5.1
thanks

**Comment by Bloodymight** [comment]
1.20.1
you can recreate this problem easily..

**Comment by LieOnLion** [comment]
fixed in 1.5.1
